import {
  Alert,
  Badge,
  BulletList,
  Card,
  CodeBlock,
  CopyButton,
  EmptyState,
  ProseBlock,
  ResultMeta,
} from '../common'
import { humanise } from '../../utils/errorMessages'

/**
 * Task-specific renderers for Developer Agent output.
 *
 * The backend goes to some trouble not to fabricate: it nulls out line
 * numbers it cannot verify, refuses to claim tests were run, and downgrades
 * diagnostic confidence when evidence is thin. This component's job is to
 * carry that honesty through to the screen rather than tidying it away.
 */

const SEVERITY_TONE = {
  critical: 'red',
  high: 'orange',
  medium: 'amber',
  low: 'sky',
  info: 'slate',
}

const SEVERITY_ORDER = ['critical', 'high', 'medium', 'low', 'info']

const CONFIDENCE_TONE = {
  confirmed: 'emerald',
  likely: 'amber',
  possible: 'slate',
}

const CONFIDENCE_EXPLANATION = {
  confirmed: 'The supplied code plainly shows this cause.',
  likely: 'Strongly suggested by the code and error, but not proven.',
  possible: 'One plausible explanation among several.',
}

function Section({ title, children }) {
  if (!children) return null
  return (
    <div>
      <h3 className="text-sm font-semibold text-slate-900">{title}</h3>
      <div className="mt-2">{children}</div>
    </div>
  )
}

function ListSection({ title, items }) {
  if (!items?.length) return null
  return (
    <Section title={title}>
      <BulletList items={items} />
    </Section>
  )
}

export default function DeveloperResult({ task, result, isSubmitting }) {
  if (isSubmitting) {
    return (
      <Card title="Result">
        <EmptyState icon="◌" title="Working…" description="The AI is analysing your code." />
      </Card>
    )
  }

  if (!result) {
    return (
      <Card title="Result">
        <EmptyState
          title="No result yet"
          description="Pick a task, paste your code and run it to see output here."
        />
      </Card>
    )
  }

  const renderers = {
    generate: GenerateResult,
    explain: ExplainResult,
    review: ReviewResult,
    refactor: RefactorResult,
    tests: TestsResult,
    debug: DebugResult,
    document: DocumentResult,
  }
  const Renderer = renderers[task]

  return (
    <Card title="Result">
      <div className="space-y-5">
        <Renderer result={result} />
      </div>
      <ResultMeta result={result} />
    </Card>
  )
}

function GenerateResult({ result }) {
  return (
    <>
      <CodeBlock code={result.code} label={result.language || 'Generated code'} />
      <Section title="Explanation">
        <ProseBlock text={result.explanation} />
      </Section>
      {result.usage_example && (
        <Section title="Usage example">
          <CodeBlock code={result.usage_example} label="Example" />
        </Section>
      )}
      <ListSection title="Assumptions" items={result.assumptions} />
      <ListSection title="Limitations" items={result.limitations} />
      {/* The backend forbids claiming the code was run; say so plainly. */}
      <Alert variant="info" title="Not executed">
        This code was generated by an AI model and has not been run or verified.
      </Alert>
    </>
  )
}

function ExplainResult({ result }) {
  return (
    <>
      <Section title="Summary">
        <ProseBlock text={result.summary} />
      </Section>
      <ListSection title="Step by step" items={result.line_by_line_explanation} />
      <ListSection title="Important concepts" items={result.important_concepts} />
      {result.potential_issues?.length > 0 && (
        <Section title="Potential issues">
          <BulletList items={result.potential_issues} />
        </Section>
      )}
    </>
  )
}

function ReviewResult({ result }) {
  const issues = [...(result.issues ?? [])].sort(
    (a, b) => SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity),
  )

  return (
    <>
      {result.overall_assessment && (
        <Section title="Overall assessment">
          <ProseBlock text={result.overall_assessment} />
        </Section>
      )}

      <Section title={`Findings (${issues.length})`}>
        {issues.length === 0 ? (
          <p className="text-sm text-slate-500">No issues were reported.</p>
        ) : (
          <ul className="space-y-3">
            {issues.map((issue, index) => (
              <li
                key={index}
                className="rounded-lg border border-slate-200 p-4"
              >
                <div className="flex flex-wrap items-center gap-2">
                  <Badge tone={SEVERITY_TONE[issue.severity] ?? 'slate'}>
                    {humanise(issue.severity)}
                  </Badge>
                  {issue.category && <Badge>{humanise(issue.category)}</Badge>}
                  {/* The backend nulls any line it cannot point to in the
                      source. Never render 0 or invent a number. */}
                  <span className="text-xs text-slate-500">
                    {typeof issue.line === 'number' ? `Line ${issue.line}` : 'Line not specified'}
                  </span>
                </div>
                {issue.problem && (
                  <p className="mt-2 text-sm text-slate-800">{issue.problem}</p>
                )}
                {issue.recommendation && (
                  <p className="mt-2 text-sm text-slate-600">
                    <span className="font-medium text-slate-700">Suggestion: </span>
                    {issue.recommendation}
                  </p>
                )}
              </li>
            ))}
          </ul>
        )}
      </Section>

      <ListSection title="Positive points" items={result.positive_points} />
      {result.summary && (
        <Section title="What to fix first">
          <ProseBlock text={result.summary} />
        </Section>
      )}
    </>
  )
}

function RefactorResult({ result }) {
  return (
    <>
      {result.original_intent && (
        <Section title="Original intent">
          <ProseBlock text={result.original_intent} />
        </Section>
      )}
      <CodeBlock code={result.refactored_code} label="Refactored code" />
      <ListSection title="Changes made" items={result.changes} />
      {result.reasoning && (
        <Section title="Reasoning">
          <ProseBlock text={result.reasoning} />
        </Section>
      )}
      {result.tradeoffs?.length > 0 && (
        <Section title="Trade-offs and things to check">
          <BulletList items={result.tradeoffs} />
        </Section>
      )}
      <Alert variant="info" title="Behaviour not verified">
        The refactor aims to preserve behaviour, but it has not been executed or
        tested by this system. Review it before use.
      </Alert>
    </>
  )
}

function TestsResult({ result }) {
  return (
    <>
      {/* The single most important honesty label in the app. The backend
          always sends executed: false, because nothing here runs tests. */}
      {result.executed !== true && (
        <Alert variant="warning" title="Tests were generated but not executed">
          {result.disclaimer ??
            'These tests were produced by an AI model. They have not been run or verified.'}
        </Alert>
      )}

      {result.framework && (
        <p className="text-sm text-slate-600">
          Framework: <span className="font-medium text-slate-800">{result.framework}</span>
        </p>
      )}

      <CodeBlock code={result.test_code} label="Test code" />

      {result.test_cases?.length > 0 && (
        <Section title={`Proposed test cases (${result.test_cases.length})`}>
          <ul className="space-y-2">
            {result.test_cases.map((testCase, index) => (
              <li key={index} className="rounded-lg border border-slate-200 p-3">
                <div className="flex flex-wrap items-center gap-2">
                  <code className="font-mono text-sm text-slate-800">{testCase.name}</code>
                  {testCase.category && <Badge>{humanise(testCase.category)}</Badge>}
                </div>
                {testCase.description && (
                  <p className="mt-1.5 text-sm text-slate-600">{testCase.description}</p>
                )}
                {testCase.expected_behavior && (
                  <p className="mt-1 text-sm text-slate-500">
                    Expected: {testCase.expected_behavior}
                  </p>
                )}
              </li>
            ))}
          </ul>
        </Section>
      )}

      {result.coverage_notes && (
        <Section title="Coverage notes">
          <ProseBlock text={result.coverage_notes} />
        </Section>
      )}
    </>
  )
}

function DebugResult({ result }) {
  const confidence = result.confidence ?? 'possible'

  return (
    <>
      <div className="flex flex-wrap items-center gap-2">
        <span className="text-sm font-medium text-slate-700">Confidence:</span>
        <Badge tone={CONFIDENCE_TONE[confidence] ?? 'slate'}>{humanise(confidence)}</Badge>
        {/* Spelled out so "likely" is never read as "confirmed". */}
        <span className="text-xs text-slate-500">{CONFIDENCE_EXPLANATION[confidence]}</span>
      </div>

      {result.problem && (
        <Section title="Problem">
          <ProseBlock text={result.problem} />
        </Section>
      )}
      {result.likely_cause && (
        <Section title="Likely cause">
          <ProseBlock text={result.likely_cause} />
        </Section>
      )}
      <ListSection title="Evidence from the supplied code" items={result.evidence} />
      <ListSection title="Other possible causes" items={result.other_possible_causes} />
      {result.fix && (
        <Section title="Suggested fix">
          <ProseBlock text={result.fix} />
        </Section>
      )}
      {result.fixed_code && <CodeBlock code={result.fixed_code} label="Fixed code" />}
      <ListSection title="Prevention" items={result.prevention} />

      <Alert variant="info" title="Not reproduced">
        This analysis is based only on the code and error you supplied. The
        problem was not reproduced or executed.
      </Alert>
    </>
  )
}

function DocumentResult({ result }) {
  return (
    <>
      {result.summary && (
        <Section title="Summary">
          <ProseBlock text={result.summary} />
        </Section>
      )}

      {result.documentation && (
        <Section title="Documentation">
          <div className="rounded-lg border border-slate-200 bg-slate-50 p-4">
            <div className="flex justify-end">
              <CopyButton text={result.documentation} />
            </div>
            <ProseBlock text={result.documentation} />
          </div>
        </Section>
      )}

      {result.parameters?.length > 0 && (
        <Section title="Parameters">
          {/* Wide tables scroll inside their own box, never the page. */}
          <div className="overflow-x-auto rounded-lg border border-slate-200">
            <table className="min-w-full divide-y divide-slate-200 text-sm">
              <thead className="bg-slate-50">
                <tr>
                  <th scope="col" className="px-3 py-2 text-left font-medium text-slate-600">Name</th>
                  <th scope="col" className="px-3 py-2 text-left font-medium text-slate-600">Type</th>
                  <th scope="col" className="px-3 py-2 text-left font-medium text-slate-600">Required</th>
                  <th scope="col" className="px-3 py-2 text-left font-medium text-slate-600">Description</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {result.parameters.map((parameter, index) => (
                  <tr key={index}>
                    <td className="px-3 py-2 font-mono text-slate-800">{parameter.name}</td>
                    <td className="px-3 py-2 font-mono text-slate-600">{parameter.type || '—'}</td>
                    <td className="px-3 py-2 text-slate-600">
                      {parameter.required ? 'Yes' : 'No'}
                    </td>
                    <td className="px-3 py-2 text-slate-600">{parameter.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Section>
      )}

      {result.returns && (
        <Section title="Returns">
          <p className="font-mono text-sm text-slate-800">{result.returns}</p>
        </Section>
      )}
      <ListSection title="Exceptions" items={result.exceptions} />
      {result.usage_example && <CodeBlock code={result.usage_example} label="Usage example" />}
    </>
  )
}
